apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: assessment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: assessment/worker:latest
          imagePullPolicy: Never
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/assessmentdb"
            - name: PUBSUB_EMULATOR_HOST
              value: "pubsub-emulator:8085"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1000m"