apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nodejs
  namespace: assessment
  labels:
    app: app-nodejs
    language: nodejs
    assessment: "true"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-nodejs
  template:
    metadata:
      labels:
        app: app-nodejs
        language: nodejs
    spec:
      containers:
        - name: app-nodejs
          image: assessment/app-nodejs:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/assessmentdb"
            - name: APP_PORT
              value: "3000"
            - name: PUBSUB_EMULATOR_HOST
              value: "pubsub-emulator:8085"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "2000m"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5
